Public_static/AccountDetails.html

were users can see and edit their account, filled it with dummy data

Made a simple account details page 

---

Public_static/css/index.css
Public_static/index.html

Added padding to top navigation bar, improved buttons UI, added better fonts.

Minor UI Tweaks

---

README.md

tightened up the grammar and capitalized MySQL properly

cleaned up some grammar/spelling in the readme

---

Public_static/about.html
Public_static/css/about.css

fixed a couple spelling errors and made about.html look cohesive with index.html

Updated about.html and about.css

---

Public_static/js/passport.js
package.json
server.js

This PR contains the Passport JS authentication implementation
Todo : Write unit test for the same

Change : Passport JS Authentication Implementation

---

Public_static/signup.html

Added a date picker to the birthday selection field, range shown by default on the picker is 1910-CURRENT although no restrictions are set on a manual date entry

Date picker for signup.html

---

.env.example
package-lock.json

The PASSWORD environment variable has been changed to DB_PASSWORD.

Change wrong password variable name in env.example

---

Public_static/css/signup.css~
Public_static/signup.html

The signup.css file had overridden the styles of styles.css which is changed and the background image is shown. In signup.html the navbar position is centered.

changed two files signup.css and signup.html

---

Public_static/about.html
Public_static/css/about.css

files updated are about.css and about.html.

modified about page

---

Public_static/css/signup.css

The open issue indicated the signup box was covering the navigation bar.  Made changes to the 'signup.css' file.  Modified the position and padding of .signupbox.  The signup box now appears below the menu bar.

modified position and padding of .signupbox to appear below the menu bar

---

Public_static/css/signup.css
Public_static/signup.html

Adds nav bar from index.html, and fixes other CSS / responsive layout issues on the signup page.
Should resolve: https://github.com/treyhboy/Mint/issues/46

Fix responsive layout issues on Signup page

---

Public_static/index.html

Changed index.html to bring the contact icons closer and thus to ease the navigation for the user across the page.

changed contacts display

---

routes/expenses/insertReminder.js

new comment

---

Public_static/about.html
Public_static/css/about.css
Public_static/index.html

I also noticed the navbar of the "About" was different so I decided to change it to match the navbars of the other pages.

added standard navbar and fixed responsiveness for "About" page

---

Public_static/css/signup.css
Public_static/index.html
Public_static/signup.html

###Overview###
-The nav bar on the signup page didn't match other pages. 
-The nav bar on the index.html page did not function properly.
###Changes###
-For the nav bar on the signup page, it looked completely different then the other pages. I brought in the nav bar that was on the other pages to match.
-The Nav bar on the index.html page for the 'contact' and the 'How it works' buttons didn't work, the j-query that was being used was throwing an error because it wasn't recognizing a function.
###Remaining Tasks###
-There may be other nav bar issues on other pages, but I believe the rest function properly.
-Close the tickets related to this pull request

Fixing Nav bar issues

---

.eslintrc
Public_static/js/about.js
Public_static/js/index.js
Public_static/js/login.js
Public_static/js/main.js
Public_static/js/plugins.js
Public_static/js/signup.js
package-lock.json
package.json

Let me know if these rules are acceptable and I'll continue on other files. I also changed long ternary operator in signup.js to an if statement for readability.

Setting up ESLint, these are the rules I typically use.

---

Public_static/js/login.js
Public_static/login.html
package-lock.json
package.json
server.js

Hello, I have implemented the google login in Min application. I can also do many other updates to the applications like adding other logins as well. Please, let me know about my code. 
Let me know, if there is anything else as I am really interested in contributing. Thanks.

implemented google login signup

---

Public_static/css/login.css
Public_static/login.html

I thought it might look nicer if the login screen matched the other pages. I replaced the navbar with the regular navbar, moved the sign in with google button, and made minor formatting changes.

Changed Login screen to match other pages

---

.github/workflows/test.yml

Resolve #83 
Run continuous integration for push and pull_requests
Configured used Github Actions

Continuous Integration

---

.github/workflows/test.yml
README.md

add workflow badge to readme for PRs

---

package-lock.json
package.json

> npm start error fixed. Async module was missing. Added **`async`** module.

Bug Fixed(issue #95).
